package com.lqs.kuaishou.kuaishou1801.cache.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lqs.kuaishou.kuaishou1801.cache.mode.HistoryEntity;
import com.lqs.kuaishou.kuaishou1801.cache.mode.KsMessage;

import com.lqs.kuaishou.kuaishou1801.cache.dao.HistoryEntityDao;
import com.lqs.kuaishou.kuaishou1801.cache.dao.KsMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyEntityDaoConfig;
    private final DaoConfig ksMessageDaoConfig;

    private final HistoryEntityDao historyEntityDao;
    private final KsMessageDao ksMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyEntityDaoConfig = daoConfigMap.get(HistoryEntityDao.class).clone();
        historyEntityDaoConfig.initIdentityScope(type);

        ksMessageDaoConfig = daoConfigMap.get(KsMessageDao.class).clone();
        ksMessageDaoConfig.initIdentityScope(type);

        historyEntityDao = new HistoryEntityDao(historyEntityDaoConfig, this);
        ksMessageDao = new KsMessageDao(ksMessageDaoConfig, this);

        registerDao(HistoryEntity.class, historyEntityDao);
        registerDao(KsMessage.class, ksMessageDao);
    }
    
    public void clear() {
        historyEntityDaoConfig.clearIdentityScope();
        ksMessageDaoConfig.clearIdentityScope();
    }

    public HistoryEntityDao getHistoryEntityDao() {
        return historyEntityDao;
    }

    public KsMessageDao getKsMessageDao() {
        return ksMessageDao;
    }

}
